### ISSUE TITLE
platformWorkspaceApi EnclosingTabId Throws "n.connect is not a function" Errors

### ISSUE THREAD

**Issue by BatemanVO** [trailheadapps/lwc-recipes#921]
### Summary

Using the sample _workspaceOpenSubtab_ component found in this repo, "n.connect is not a function" errors are thrown

### Salesforce Org Type

Sandbox

#### Steps to Reproduce
I've created a repo with the code I am using at [this link](https://github.com/BatemanVO/workspace-enclosing-tab-error).

I've gone into my personal Sandbox and created a new custom object, EnclosingTab__c.
- Create a single record with no fields populated
- Navigate to that record in a console environment
- Setup -> Edit Page
- Add the enclosingTabLogger component to the page layout:
![sample-page-layout](https://github.com/salesforce/lwc/assets/20998142/68d0a8ac-c750-4c0a-b756-a69410b4f472)
- Save and activate the page layout
- Experience the error:
![not-a-function-error](https://github.com/salesforce/lwc/assets/20998142/c052ab64-3bb9-4a34-a5e6-1d406d271855)

### Current Behavior

"n.connect is not a function" error is thrown when attempting to use the EnclosingTabId method imported from lightning/platformWorkspaceApi

### Expected Behavior

EnclosingTabId should provide the Id of the tab the component is loaded on

### Relevant Log Output

```shell
TypeError: n.connect is not a function
    at Array.<anonymous> (https://static.lightning.force.com/usa770s.sfdc-8tgtt5/auraFW/javascript/MFZGMnNxcWxxQVZkaERsVUY3RzNmZ3ZrcWo2bHVYSXBmeGJiLUx2eVNiWWcyNDguMTAuMy01LjAuOQ/aura_prod.js:51:44171)
    at https://static.lightning.force.com/usa770s.sfdc-8tgtt5/auraFW/javascript/MFZGMnNxcWxxQVZkaERsVUY3RzNmZ3ZrcWo2bHVYSXBmeGJiLUx2eVNiWWcyNDguMTAuMy01LjAuOQ/aura_prod.js:51:45485
    at bo (https://static.lightning.force.com/usa770s.sfdc-8tgtt5/auraFW/javascript/MFZGMnNxcWxxQVZkaERsVUY3RzNmZ3ZrcWo2bHVYSXBmeGJiLUx2eVNiWWcyNDguMTAuMy01LjAuOQ/aura_prod.js:51:45488)
    at nr (https://static.lightning.force.com/usa770s.sfdc-8tgtt5/auraFW/javascript/MFZGMnNxcWxxQVZkaERsVUY3RzNmZ3ZrcWo2bHVYSXBmeGJiLUx2eVNiWWcyNDguMTAuMy01LjAuOQ/aura_prod.js:51:30482)
    at tr (https://static.lightning.force.com/usa770s.sfdc-8tgtt5/auraFW/javascript/MFZGMnNxcWxxQVZkaERsVUY3RzNmZ3ZrcWo2bHVYSXBmeGJiLUx2eVNiWWcyNDguMTAuMy01LjAuOQ/aura_prod.js:51:30043)
    at rr (https://static.lightning.force.com/usa770s.sfdc-8tgtt5/auraFW/javascript/MFZGMnNxcWxxQVZkaERsVUY3RzNmZ3ZrcWo2bHVYSXBmeGJiLUx2eVNiWWcyNDguMTAuMy01LjAuOQ/aura_prod.js:51:30607)
    at https://static.lightning.force.com/usa770s.sfdc-8tgtt5/auraFW/javascript/MFZGMnNxcWxxQVZkaERsVUY3RzNmZ3ZrcWo2bHVYSXBmeGJiLUx2eVNiWWcyNDguMTAuMy01LjAuOQ/aura_prod.js:51:29955
    at tr (https://static.lightning.force.com/usa770s.sfdc-8tgtt5/auraFW/javascript/MFZGMnNxcWxxQVZkaERsVUY3RzNmZ3ZrcWo2bHVYSXBmeGJiLUx2eVNiWWcyNDguMTAuMy01LjAuOQ/aura_prod.js:51:29979)
    at rr (https://static.lightning.force.com/usa770s.sfdc-8tgtt5/auraFW/javascript/MFZGMnNxcWxxQVZkaERsVUY3RzNmZ3ZrcWo2bHVYSXBmeGJiLUx2eVNiWWcyNDguMTAuMy01LjAuOQ/aura_prod.js:51:30607)
    at br (https://static.lightning.force.com/usa770s.sfdc-8tgtt5/auraFW/javascript/MFZGMnNxcWxxQVZkaERsVUY3RzNmZ3ZrcWo2bHVYSXBmeGJiLUx2eVNiWWcyNDguMTAuMy01LjAuOQ/aura_prod.js:51:35186)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BatemanVO** [comment]
As noted in [the documentation](https://developer.salesforce.com/docs/component-library/bundle/lightning-platform-workspace-api/documentation), issue is because Lightning Web Security needs to be enabled in the Org instead of Lightning Locker.
